### ISSUE TITLE
convert a new promo for the website

### ISSUE THREAD

**Issue by ProgrammingMan772** [AssMod/chess-acadmey.net-#3]
remove the horsey promo add a new logo change lichess with horsey add new https://github.com/AssMod/chess-acadmey.net-/commit/3f34d76d112bc2c4f7c3e88fe38fa5cad41e77a0

**Comment by AssMod** [comment]
![e082bc82045427cd897b4a8d1d734330](https://user-images.githubusercontent.com/88207318/127768577-a483fb23-4d3a-4a7c-bbe2-b6f6819e2b86.jpg) the jpg image has been changed successfully
